Repository slackapi/python-slack-sdk, pull requests merged in 2019-08, with the labels that each got.

#501 Adding new admin and remote files API methods.
  slack/web/client.py
Labels: Priority: High, Type: Maintenance, Version: 2x

#498 Fix link to Auth Guide in readme
  README.md
Labels: Priority: Medium, Resolution: Done, Type: Docs, Version: 2x

#473 Update BlockAttachment to not send invalid JSON due to fields attribute
  slack/web/classes/attachments.py
  tests/web/classes/test_attachments.py
Labels: Priority: High, Resolution: Done, Type: Bug, Version: 2x

#490 Return callback from `RTMClient.run_on`
  slack/rtm/client.py
  tests/rtm/test_rtm_client.py
Labels: Priority: High, Resolution: Done, Type: Bug, Version: 2x
