Repository slackapi/python-slack-sdk, pull requests merged in 2019-11, with the labels that each got.

#568 Remove _validate_xoxp_token
  slack/web/base_client.py
  slack/web/client.py
  tests/web/test_web_client.py
Labels: Priority: High, Resolution: Done, Type: Enhancement, Version: 2x

#563 Remove value from LinkButtonElement
  slack/web/classes/elements.py
  tests/web/classes/test_elements.py
Labels: Priority: Medium, Type: Bug, Version: 2x

#571 Adding new admin.* API's
  slack/web/client.py
Labels: Priority: High, Type: Enhancement, Version: 2x
