Repository slackapi/python-slack-sdk, pull requests merged in 2019-05, with the labels that each got.

#414 added scheduled messages api, removed file_command_add api endpoint
  slack/web/client.py
Labels: enhancement

#413 Mpreston/files info args fix
  slack/web/client.py
Labels: bug

#423 fix the broken argument names in `channels.*`
  slack/web/client.py
Labels: bug

#425 modified comment to include the correct arg for the rtm client files
  slack/rtm/client.py
Labels: Priority - Low, RTM, docs

#428 fixed typo in Scheduled message
  slack/web/client.py
Labels: bug

#410 [WIP/Proposal] Add async client example [docs]
  documentation_v2/examples/asyncio.md
Labels: docs
