Repository slackapi/python-slack-sdk, pull requests merged in 2019-06, with the labels that each got.

#435 The methods were incorrectly cased and would fail
  slack/web/client.py
Labels: Priority: High, Type: Bug, Version: 2x

#440 Update setup.py
  setup.py
Labels: Priority: Medium, Resolution: Done, Type: Enhancement, Version: 2x

#455 Update docs for async functionality
  README.md
Labels: Priority: Medium, Type: Docs, Version: 2x

#457 Use kwarg for web_client.im_open in tutorial docs
  tutorial/03-responding-to-slack-events.md
Labels: Priority: Low, Type: Docs, Version: 2x

#462 Fix "02 - Building a message" link
  tutorial/03-responding-to-slack-events.md
Labels: Priority: Low, Type: Docs, Version: 2x

#446 Fixing 415 - Converting the typing function to async
  .gitignore
  slack/rtm/client.py
  slack/web/base_client.py
  slack/web/client.py
  tests/rtm/test_rtm_client.py
  tests/rtm/test_rtm_client_functional.py
Labels: Priority: High, Type: Bug, Version: 2x

#400 Mostly type-hinted helper classes for inclusion in v2
  slack/errors.py
  slack/web/classes/__init__.py
  slack/web/classes/actions.py
  slack/web/classes/attachments.py
  slack/web/classes/blocks.py
  slack/web/classes/dialog_elements.py
  slack/web/classes/dialogs.py
  slack/web/classes/elements.py
  slack/web/classes/interactions.py
  slack/web/classes/messages.py
  slack/web/classes/objects.py
  slack/web/classes/readme.md
  tests/web/classes/__init__.py
  tests/web/classes/test_actions.py
  tests/web/classes/test_attachments.py
  tests/web/classes/test_blocks.py
  tests/web/classes/test_dialogs.py
  tests/web/classes/test_elements.py
  tests/web/classes/test_objects.py
Labels: Priority: Medium, Type: Enhancement, Version: 2x

#454 Signature verification staticmethod on base client
  slack/web/base_client.py
Labels: Priority: Low, Type: Enhancement, Version: 2x

#453 Handle case in which aiohttp closes the websocket due to lack of ping responses.
  slack/rtm/client.py
Labels: Priority: High, Type: Bug, Version: 2x
