Repository slackapi/python-slack-sdk, pull requests merged in 2020-12, with the labels that each got.

#882 Add default team_id to WebClient constructor args
  slack_sdk/web/async_base_client.py
  slack_sdk/web/base_client.py
  slack_sdk/web/internal_utils.py
  slack_sdk/web/legacy_base_client.py
  tests/slack_sdk/web/test_web_client.py
  tests/slack_sdk_async/web/test_async_web_client.py
  tests/web/test_web_client.py
Labels: Version: 3x, enhancement, web-client

#885 Update PlainTextInputElement description
  slack_sdk/models/blocks/block_elements.py
Labels: Version: 3x, bug, docs, untriaged, web-client

#890 Fix #889 by correcting the team_join event handler
  tutorial/03-responding-to-slack-events.md
  tutorial/PythOnBoardingBot/app.py
  tutorial/PythOnBoardingBot/async_app.py
Labels: Version: 3x, bug, docs

#897 the timestamp for Slack-post never changes, it is effectivly an ID
  tutorial/PythOnBoardingBot/app.py
Labels: Version: 3x, docs, semver:patch

#898 Update channel char limit to 80
  docs-src-v2/conversations.rst
  docs-src/web/index.rst
  docs-v2/.buildinfo
  docs-v2/conversations.html
  docs/.buildinfo
  docs/web/index.html
Labels: Version: 2x, Version: 3x, docs

#896 Update WebClient to accept not only list but also tuple
  slack_sdk/web/async_client.py
  slack_sdk/web/client.py
  slack_sdk/web/legacy_client.py
  tests/slack_sdk_async/web/test_web_client_coverage.py
Labels: Version: 3x, enhancement, web-client

#904 Fix #903 by parsing in ActionsBlock
  slack_sdk/models/blocks/blocks.py
  tests/slack_sdk/web/classes/test_blocks.py
Labels: Version: 3x, bug

#905 Fix #903 by parsing elements in ActionsBlock
  slack/web/classes/blocks.py
  tests/web/classes/test_blocks.py
Labels: Version: 2x, bug
