Repository slackapi/python-slack-sdk, pull requests merged in 2020-03, with the labels that each got.

#601 Tutorial markdown cleanup
  tutorial/01-creating-the-slack-app.md
  tutorial/02-building-a-message.md
  tutorial/03-responding-to-slack-events.md
  tutorial/04-running-the-app.md
  tutorial/README.md
Labels: docs

#618 Add py.typed file to package distribution
  MANIFEST.in
Labels: Priority: Medium, Version: 2x, bug, semver:patch

#629 Fix a few misspelling words in docs
  docs-src/changelog.rst
  docs-src/index.rst
  docs-src/real_time_messaging.rst
  docs/_static/basic.css
  docs/_static/classic.css
  docs/_static/doctools.js
  docs/_static/documentation_options.js
  docs/_static/language_data.js
  docs/_static/searchtools.js
  docs/_static/sidebar.js
  docs/basic_usage.html
  docs/changelog.html
  docs/index.html
  docs/real_time_messaging.html
  docs/search.html
  docs/searchindex.js
  tutorial/01-creating-the-slack-app.md
  tutorial/03-responding-to-slack-events.md
Labels: docs

#636 Fix #635 DatePickerElement initial_date validation is incorrect
  slack/web/classes/elements.py
  tests/web/classes/test_elements.py
Labels: bug
