Repository slackapi/python-slack-sdk, pull requests merged in 2021-11, with the labels that each got.

#1132 Add team.* & admin.users.session.resetBulk APIs
  integration_tests/web/test_admin_users_session.py
  integration_tests/web/test_team.py
  slack_sdk/web/async_client.py
  slack_sdk/web/client.py
  slack_sdk/web/legacy_client.py
  tests/slack_sdk_async/web/test_web_client_coverage.py
Labels: enhancement, web-client, Version: 3x

#1135 Fix #1127 Add more docstrings to slack_sdk.models classes
  slack_sdk/models/blocks/basic_components.py
  slack_sdk/models/blocks/block_elements.py
  slack_sdk/models/blocks/blocks.py
  tests/slack_sdk/models/test_elements.py
Labels: enhancement, web-client, Version: 3x

#1136 Upgrade pytype to 2021.11.18
  .github/workflows/pytype.yml
  slack_sdk/models/messages/__init__.py
  slack_sdk/oauth/installation_store/models/bot.py
  slack_sdk/oauth/installation_store/models/installation.py
  slack_sdk/oauth/state_store/sqlalchemy/__init__.py
Labels: Version: 3x

#1137 Fix #1131 Add the method to check equality in Block Kit model classes
  slack_sdk/models/basic_objects.py
  tests/slack_sdk/models/test_blocks.py
  tests/slack_sdk/models/test_elements.py
  tests/slack_sdk/models/test_objects.py
  tests/slack_sdk/models/test_views.py
Labels: enhancement, web-client, Version: 3x

#1139 Fix 1086 add interactivity patterns in SocketModeClient docs
  docs-src/socket-mode/index.rst
Labels: docs

#1140 Add focus_on_load support in Block Kit
  slack_sdk/models/blocks/block_elements.py
  tests/slack_sdk/models/test_elements.py
Labels: web-client, Version: 3x

#1141 Add GitHub stale action for better triaging issues
  .github/workflows/triage-issues.yml
Labels: enhancement
