Repository slackapi/python-slack-sdk, pull requests merged in 2021-04, with the labels that each got.

#988 Setting a default value for select_options for ViewStateValue
  slack_sdk/models/views/__init__.py
  tests/slack_sdk/models/test_views.py
Labels: Version: 3x, web-client

#993 Fix #990 slack_sdk.models.blocks.Option's description value is invalid in blocks
  slack_sdk/models/blocks/basic_components.py
  tests/slack_sdk/models/test_objects.py
  tests/slack_sdk/models/test_views.py
Labels: Version: 3x, bug, web-client

#995 Fix #976 Add deletion methods to InstallationStore
  slack_sdk/oauth/installation_store/amazon_s3/__init__.py
  slack_sdk/oauth/installation_store/async_cacheable_installation_store.py
  slack_sdk/oauth/installation_store/async_installation_store.py
  slack_sdk/oauth/installation_store/cacheable_installation_store.py
  slack_sdk/oauth/installation_store/file/__init__.py
  slack_sdk/oauth/installation_store/installation_store.py
  slack_sdk/oauth/installation_store/sqlalchemy/__init__.py
  slack_sdk/oauth/installation_store/sqlite3/__init__.py
  tests/slack_sdk/oauth/installation_store/test_file.py
  tests/slack_sdk/oauth/installation_store/test_interface.py
  tests/slack_sdk/oauth/installation_store/test_simple_cache.py
  tests/slack_sdk/oauth/installation_store/test_sqlalchemy.py
  tests/slack_sdk/oauth/installation_store/test_sqlite3.py
Labels: Version: 3x, enhancement, oauth

#996 version 3.5.0rc1 release
  slack_sdk/version.py
Labels: Version: 3x, enhancement, semver:minor

#1001 Fix #1000 RTMClient v2 still requires aiohttp installed (even though it's unused)
  docs-src/real_time_messaging.rst
  slack_sdk/rtm/v2/__init__.py
  slack_sdk/rtm_v2/__init__.py
  tests/slack_sdk/rtm_v2/__init__.py
  tests/slack_sdk/rtm_v2/test_rtm_v2.py
Labels: Version: 3x, bug, rtm-client

#1004 Fix #1002 ConversationFilter missing new optional field exclude_external_shared_channels
  slack_sdk/models/blocks/block_elements.py
Labels: Version: 3x, enhancement, semver:minor, web-client

#1006 Fix #1003 threading.Thread.setDaemon has been deprecated in Python 3.10
  integration_tests/rtm/test_issue_569.py
  integration_tests/rtm/test_issue_605.py
  integration_tests/rtm/test_issue_631.py
  integration_tests/rtm/test_issue_701.py
  integration_tests/rtm/test_rtm_client.py
  slack_sdk/socket_mode/interval_runner.py
Labels: Version: 3x, socket-mode, tests

#1008 Fix url typo
  slack_sdk/models/blocks/block_elements.py
Labels: Version: 3x, docs, web-client

#1010 [#1009] fix mistake in webclient dependency version range
  setup.py
Labels: semver:patch
