Repository slackapi/python-slack-sdk, pull requests merged in 2023-05, with the labels that each got.

#1362 Add metadata support to Incoming Webhooks
  integration_tests/webhook/test_async_webhook.py
  integration_tests/webhook/test_webhook.py
  slack_sdk/webhook/async_client.py
  slack_sdk/webhook/client.py
Labels: bug, web-client, Version: 3x

#1365 Add create_tables() to SQLAlchemyOAuthStateStore
  slack_sdk/oauth/state_store/sqlalchemy/__init__.py
Labels: Version: 3x, oauth, cla:signed

#1368 Add cursor based pagination to team.accessLogs
  slack_sdk/web/async_client.py
  slack_sdk/web/client.py
  slack_sdk/web/legacy_client.py
Labels: enhancement, web-client, Version: 3x

#1366 Add author_subname to attachment models
  slack_sdk/models/attachments/__init__.py
  tests/slack_sdk/models/test_attachments.py
Labels: enhancement, web-client, Version: 3x

#1367 Add built in server error retry handlers
  slack_sdk/http_retry/builtin_async_handlers.py
  slack_sdk/http_retry/builtin_handlers.py
Labels: enhancement, web-client, Version: 3x, cla:signed

#1372 fix[builtin_handlers]: ServerErrorRetryHandler, renaming _can_retry_async -> _can_retry
  slack_sdk/http_retry/builtin_handlers.py
Labels: enhancement, web-client, Version: 3x, cla:signed

#1375 Update GitHub Action steps to use Node 16
  .github/workflows/ci-build.yml
  .github/workflows/pytype.yml
Labels: tests

#1374 Fix #1369 ImageBlock title parsing defaults to incorrect behaviour when given a string
  slack_sdk/models/blocks/blocks.py
  tests/slack_sdk/models/test_blocks.py
Labels: bug, web-client, Version: 3x

#1376 Use codecov/codecov-action@v3 to upload code coverage
  .github/workflows/ci-build.yml
Labels: tests
