Repository slackapi/python-slack-sdk, pull requests merged in 2024-01, with the labels that each got.

#1448 fixed broken link related to documenation of modals.
  docs/api-docs/slack_sdk/index.html
  docs/api-docs/slack_sdk/web/async_client.html
  docs/api-docs/slack_sdk/web/client.html
  docs/api-docs/slack_sdk/web/index.html
  docs/api-docs/slack_sdk/web/legacy_client.html
  slack_sdk/web/async_client.py
  slack_sdk/web/client.py
  slack_sdk/web/legacy_client.py
Labels: docs, web-client, Version: 3x, cla:signed

#1447 fix #1446: monitor dies when exceptions raised before monitor created.
  slack_sdk/socket_mode/aiohttp/__init__.py
  tests/slack_sdk/socket_mode/mock_socket_mode_server.py
  tests/slack_sdk/socket_mode/mock_web_api_server.py
  tests/slack_sdk/socket_mode/test_builtin.py
  tests/slack_sdk_async/socket_mode/test_aiohttp.py
  tests/slack_sdk_async/socket_mode/test_interactions_aiohttp.py
  tests/slack_sdk_async/socket_mode/test_websockets.py
Labels: bug, Version: 3x, socket-mode, cla:signed

#1449 feat: add download badge in readme
  README.md
Labels: docs

#1456 fix: optional dependency install
  pyproject.toml
Labels: bug

#1452 Fix #1450 slack_file in image block/element
  slack_sdk/models/blocks/basic_components.py
  slack_sdk/models/blocks/block_elements.py
  slack_sdk/models/blocks/blocks.py
  tests/slack_sdk/models/test_blocks.py
  tests/slack_sdk/models/test_elements.py
Labels: enhancement, web-client, Version: 3x
